# Generated by Django 5.2.6 on 2025-09-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_group_alter_student_options_alter_student_group_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
