# Generated by Django 5.2.6 on 2025-09-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_group_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group_name',
        ),
    ]
