# Generated by Django 5.2.6 on 2025-12-17 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_comment_author_remove_project_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='picture',
            field=models.ImageField(null=True, upload_to='tasks', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='task',
            name='picture',
            field=models.ImageField(null=True, upload_to='tasks', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='column',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.project', verbose_name='Проект'),
        ),
    ]
