# Generated by Django 5.2.6 on 2026-02-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
