# Generated by Django 5.2.6 on 2026-03-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_userprofile_options_alter_userprofile_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_create', 'Имеет право создавать'), ('can_see_page', 'Может смотреть на страницу')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
