# Generated by Django 5.2.6 on 2026-03-02 10:08

from django.db import migrations, models
import pyotp
import tqdm
def fill_totp_field(apps, schema_editor):
    UserProfile = apps.get_model("tasks", "UserProfile")
    for u in tqdm.tqdm(UserProfile.objects.all()):
        u.totp_key = pyotp.random_hex()
        u.save()



class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='totp_key',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.RunPython(fill_totp_field),
    ]
