# Generated by Django 5.2.6 on 2026-03-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_userprofile_totp_key'),
    ]

    operations = [
    ]
