# Generated by Django 5.2.6 on 2026-03-02 10:49

from django.db import migrations, models
import pyotp
import tqdm
def fill_totp_field(apps, schema_editor):
    UserProfile = apps.get_model("tasks", "UserProfile")
    for u in tqdm.tqdm(UserProfile.objects.all()):
        u.totp_key = pyotp.random_hex()
        u.save()

class Migration(migrations.Migration):

    

    dependencies = [
        ('tasks', '0011_fill_existing_totp_keys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_create', 'Имеет право создавать'), ('can_see_page', 'Может смотреть на страницу')]},
        ),
    ]
