# Generated by Django 5.2.6 on 2026-03-04 02:42

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_userprofile_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='totp_key',
            field=models.CharField(default=pyotp.random_base32, max_length=128, null=True),
        ),
    ]
